package importcmd

import "github.com/jfrog/jfrog-cli-core/v2/utils/coreutils"

var Usage = []string{"config import <server token>"}

func GetDescription() string {
	return `Imports a server configuration from a server token. A server token is generated by the "` + coreutils.GetCliExecutableName() + ` config export <Server ID>" command.`
}
