package importcmd

const Description string = `Imports a server configuration from a server token. A server token is generated by the "jfrog rt c export <Server ID>" command.`

var Usage = []string{"jfrog rt c import <server token>"}

const Arguments string = `	server token
		Token generated by the "jfrog rt c export <Server ID>" command.`
