package importcmd

import "github.com/jfrog/jfrog-cli-core/v2/utils/coreutils"

var Usage = []string{"config import <Config Token>"}

func GetDescription() string {
	return `Imports a server configuration from a Config Token. A Config Token is generated by the "` + coreutils.GetCliExecutableName() + ` config export <Server ID>" command.`
}

func GetAIDescription() string {
	return `Restore a server configuration from a Config Token string produced by 'jf c export'. The token bundles URL and credentials so a new machine can be provisioned in one step.

When to use:
- Bootstrapping a CI runner or new dev machine without re-prompting for credentials.
- Migrating configurations between hosts.

Prerequisites:
- A Config Token created with 'jf c export <server-id>' on the source machine.

Common patterns:
  $ jf c import eyJ2ZXJzaW9uIjoxLCJjb2RlIjoiLi4uIn0=

Gotchas:
- The token contains credentials; treat it like a password and never commit it.
- The imported server ID inherits from the original; if it collides with an existing one, the import fails.

Related: jf c export, jf c add, jf c show`
}
