package mvn

const Description = "Run Maven build."

var Usage = []string{`jfrog rt mvn "<goals and options>" <config file path> [command options]`, `jfrog rt mvn "<goals and options> -f path/to/pom.xml" <config file path> [command options]`}

const Arguments string = `	goals and options
		Goals and options to run with mvn command.

	config file path
		Path to a configuration file generated by the "jfrog rt mvnc" command.`

const EnvVar string = `	JFROG_CLI_JCENTER_REMOTE_SERVER
		Configured Artifactory server ID from which to download the jar needed by the mvn command.
		The Artifactory server should include a remote maven repository named jcenter, which proxies jcenter.

	JFROG_CLI_JCENTER_REMOTE_REPO
		[Default: jcenter]
		Can be optionally used with the JFROG_CLI_JCENTER_REMOTE_SERVER environment variable.
		Determines the name of the remote repository to use.`
