package mvn

const Description = "Run Maven build."

var Usage = []string{`jfrog rt mvn "<goals and options>" <config file path> [command options]`, `jfrog rt mvn "<goals and options> -f path/to/pom.xml" <config file path> [command options]`}

const Arguments string = `	goals and options
		Goals and options to run with mvn command.

	config file path
		Path to a configuration file generated by the "jfrog rt mvnc" command.`
