package mvn

const Description = "Run Maven."

var Usage = []string{"jfrog mvn <goals and options> <config file path> [command options]"}

const Arguments string =
`	goals and options
		Goals and options to run with mvn command.

	config file path
		Path to a configuration file generated by the "jfrog rt mvnc" command.`