---
name: "🐛 Bug Report" [Help us improve JFrog CLI! Take a 3-minute survey](https://www.surveymonkey.com/r/JFCLIGTB)
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        What is the problem? A clear and concise description of the bug.
        Note: Issues related to JFrog security features such as Xray, audit, scan, etc., should be opened on the [jfrog-cli-security repository](https://github.com/jfrog/jfrog-cli-security/issues/new?template=bug_report.yml).
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: |
        Please include full errors, uncaught exceptions, screenshots, and relevant logs.
        Using environment variable JFROG_CLI_LOG_LEVEL="DEBUG" upon running the command will provide more log information.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: |
        Provide steps to reproduce the behavior.
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: |
        What did you expect to happen?
    validations:
      required: false

  - type: input
    id: cli-version
    attributes:
      label: JFrog CLI version
      description: using "jf --version"
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating system type and version
    validations:
      required: true

  - type: input
    id: rt-version
    attributes:
      label: JFrog Artifactory version
    validations:
      required: false

  - type: input
    id: xr-version
    attributes:
      label: JFrog Xray version
    validations:
      required: false
