package gradle

const Description = "Run Gradle."

var Usage = []string{"jfrog gradle <tasks and options> <config file path> [command options]"}

const Arguments string =
`	tasks and options
		Tasks and options to run with gradle command.

	config file path
		Path to a configuration file generated by the "jfrog rt gradlec" command.`