name: 'Setup Ghost Frog'
description: 'Install JFrog CLI and enable transparent package manager interception'
author: 'JFrog'
branding:
  icon: 'package'
  color: 'green'

inputs:
  jfrog-url:
    description: 'JFrog Platform URL'
    required: false
  jfrog-access-token:
    description: 'JFrog access token (recommend using secrets)'
    required: false
  jf-version:
    description: 'JFrog CLI version to install (default: latest)'
    required: false
    default: 'latest'
  enable-aliases:
    description: 'Enable package manager aliases (default: true)'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install JFrog CLI
      shell: bash
      run: |
        echo "ðŸ“¦ Installing JFrog CLI..."
        if [ "${{ inputs.jf-version }}" == "latest" ]; then
          curl -fL https://install-cli.jfrog.io | sh
        else
          curl -fL https://install-cli.jfrog.io | sh -s v${{ inputs.jf-version }}
        fi
        sudo mv jf /usr/local/bin/
        jf --version
    
    - name: Configure JFrog CLI
      shell: bash
      if: ${{ inputs.jfrog-url != '' }}
      run: |
        echo "ðŸ”§ Configuring JFrog CLI..."
        if [ -n "${{ inputs.jfrog-access-token }}" ]; then
          jf config add ghost-frog \
            --url="${{ inputs.jfrog-url }}" \
            --access-token="${{ inputs.jfrog-access-token }}" \
            --interactive=false
          jf config use ghost-frog
          echo "âœ… JFrog CLI configured with ${{ inputs.jfrog-url }}"
        else
          echo "âš ï¸  No access token provided, skipping configuration"
        fi
    
    - name: Install Ghost Frog Aliases
      shell: bash
      if: ${{ inputs.enable-aliases == 'true' }}
      run: |
        echo "ðŸ‘» Installing Ghost Frog package aliases..."
        jf package-alias install
        
        # Add to GitHub Actions PATH
        echo "$HOME/.jfrog/package-alias/bin" >> $GITHUB_PATH
        
        # Show status
        echo ""
        jf package-alias status
        
        echo ""
        echo "âœ… Ghost Frog is ready! Package manager commands will be transparently intercepted."
        echo ""
        echo "Examples:"
        echo "  npm install    â†’ jf npm install"
        echo "  mvn package    â†’ jf mvn package"
        echo "  pip install    â†’ jf pip install"
        echo "  go build       â†’ jf go build"
