version: 1
type: gradle

resolver:
    repo: ${JcenterRemoteRepo}
    username: ${RT_USERNAME}
    password: ${RT_PASSWORD}
    url: ${RT_URL}
deployer:
    repo: ${REPO1}
    username: ${RT_USERNAME}
    password: ${RT_PASSWORD}
    url: ${RT_URL}