name: Close inactive issues
on:
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          # Only check issues labeled as bugs
          only-labels: "bug"
          days-before-issue-stale: 90
          days-before-issue-close: 7
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked as stale due to 90 days of inactivity. If you wish to keep it open, please remove the stale label or leave a comment; otherwise, it will be closed in 7 days."
          close-issue-message: "This issue was closed due to 7 days of inactivity after being marked as stale. Feel free to reopen it if it remains relevant."
          days-before-pr-close: false
          days-before-pr-stale: false
          debug-only: 'true'
          operations-per-run: 100  # Process only 100 issues per run
          ascending: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
