name: "OIDC Test"
on: push

permissions:
  id-token: write
  contents: read
env:
  JFROG_CLI_LOG_LEVEL: DEBUG
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4

      # Setup CLI to config server
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      # Build the current version of CLI
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build CLI
        run: ./build/build.sh

      - name: Get ID Token (cURL method)
        id: idtoken
        run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_OUTPUT 

      - name: CLI exchange token
        run: ./jf eot --oidc-token-id=${{ steps.idtoken.outputs.ID_TOKEN }}

      - name: CLI ping
        run: ./jf c add --url=${{ vars.JF_URL }} --access-token=${{ env.JFROG_CLI_OIDC_TOKEN }} --interactive=false --overwrite=true && ./jf rt ping