name: "OIDC Test"
on: push

permissions:
  id-token: write
  contents: read
env:
  JFROG_CLI_LOG_LEVEL: DEBUG
  JFROG_CLI_OIDC_PROVIDER_TYPE: GitHub
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4

      #      # Setup CLI to config server
      #      - uses: jfrog/setup-jfrog-cli@v4
      #        env:
      #          JF_URL: ${{ vars.JF_URL }}
      #          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      # Build the current version of CLI
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build CLI
        run: ./build/build.sh

      - name: Get ID Token and Exchange Token
        run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
          export JFROG_CLI_OIDC_EXCHANGE_TOKEN_ID=${ID_TOKEN}
          ./jf c add --url=https://ecosysjfrog.jfrog.io --oidc-provider=setup-jfrog-cli-test --interactive=false

      - name: Run CLI command
        run: ./jf rt ping